### PR TITLE
Equivalences

### PR DESCRIPTION
**Pull request by bgyori**
This pull request adds a new `equivalences.csv` file which maps entries in outside name spaces into Bioentities.

### CODE REVIEW

**Comment by johnbachman** [comment]
What was the reason behind switching from "PFAM" to "PF"?

**Comment by johnbachman** [comment]
Aha, I see this was because PF is used by REACH. But doesn't TRIPS use "PFAM"?

**Comment by hickst** [comment]
I like the translations table idea. One nit: Reach is committed to using the MIRIAM namespace and identifier patterns, whenever possible, so we will producing the namespace 'pfam' for PFAM IDs, per the "official" MIRIAM registry page: http://www.ebi.ac.uk/miriam/main/collections/MIR:00000028
Note that most of the MIRIAM namespaces are also lowercase.

**Comment by hickst** [comment]
Ah drats...I just noticed that BEL uses uppercase namespace strings, and you're being consistent with them, right?

**Comment by hickst** [comment]
@johnbachman PF should not be used by Reach as the namespace string. As commented above, we are using the MIRIAM-registered string 'pfam'. However, I think there is confusion because the PFAM Identifier Pattern **includes** a leading 'PF' (many ID patterns do not include leading abbreviation-like characters but some do (see Gene Ontology, for instance)). So, Reach should produce identifications like this: 'pfam:PF00071'

**Comment by johnbachman** [comment]
Aha, yes, I was confused by the PF prefix.

**Comment by bgyori** [comment]
@hickst these name spaces I chose are the most convenient from the perspective of INDRA and the existing grounding map (which uses IP for InterPro). REACH doesn't need to change at all - we just need to do the right mapping on our end. We should probably define all the namespaces somewhere in the repo to make them clear.

**Comment by hickst** [comment]
OK, thanks for the clarification.

**Pull request merged**
