### PR TITLE
grounding of entities 151-200, 301-330

### PR DESCRIPTION
**Pull request by subkar**

### CODE REVIEW

**Comment by jmuhlich** [comment]
I think there is a line-ending problem here. The diff is reported as removing -864 lines, +1 line, which is obviously wrong! Kartik, open it in Excel and "save as..." then choose windows-format csv.

**Comment by jmuhlich** [comment]
Nevermind I'll fix it.

**Comment by johnbachman** [comment]
There also appear to be a number of lines where INDRA is listed as a namespace but there is no INDRA ID, e.g.:

```
AMPKalpha,INDRA,,,,,
RSK,INDRA,,,,,
NFAT,INDRA,,,,,
BMP,INDRA,,,,,
death receptors,INDRA,,,,,
IL-12,INDRA,,,,,
```

and other entries that look like they should be grounded but aren't:

```
GTPase,,,,,,
IL-1,,,,,,
Miz1,,,,,,
TSC,,,,,,
```

(We can add an INDRA family for GTPase.)

**Comment by jmuhlich** [comment]
I fixed this up and resubmitted it as #4.

**Comment by subkar** [comment]
Thanks for fixing those issues. NB, SMC, TSC, D2 were a few entities I did not get to at my first pass because the sentences were not up at the time. I think NB is a cell line. I will fix those too.

**Pull request closed without merging**
